name: Python CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Build and Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.13

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r converter_cicd/requirements.txt
    - name: Run Tests
      run: pytest

  deploy:
    name: Deploy to Remote Server
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Deploy via SSH
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ${{ secrets.DEPLOY_USER }}
        password: ${{ secrets.DEPLOY_PASS }}
        port: ${{ secrets.DEPLOY_PORT }}
        script: |
          mkdir -p ~/python-ci-cd
          rm -rf ~/python-ci-cd/*
          tar -czf ~/python-ci-cd/code.tar.gz -C $GITHUB_WORKSPACE .
          cd ~/python-ci-cd-enum
          tar -xzf code.tar.gz
          echo "Deployment successful!"
